jdx/hk

- pkl/builtins/terraform.pkl
The `terraform fmt` command can also check and fix `.tfvars` files which are used to provide values for any variables defined in a Terraform project.
> Include `.tfvars` files in Terraform builtin

- src/cli/run/mod.rs
`hk run` crashes. Probably is better to have it show the `hk run` help, kinda like bare `hk` does.
Before:
```sh
❯ hk run
thread 'main' panicked at src/cli/run/mod.rs:34:28:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After:
```sh
❯ hk run
Run a hook
Usage: run [OPTIONS] [FILES]... [COMMAND]
Commands:
commit-msg          [aliases: cm]
pre-commit          Sets up git hooks to run hk [aliases: pc]
pre-push            [aliases: pp]
prepare-commit-msg  [aliases: pcm]
help                Print this message or the help of the given subcommand(s)
(etc)
```
Decided against adding a unit test because I didn't have a good feel for the patterns you want to use there.
> Make `hk run` show `run` help instead of crashing

- .github/workflows/docs.yml
This Docs workflow only makes sense on the source repo, and fails on forks. Adding these conditionals is [the GitHub-recommended way](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution) to skip a job on a fork.
> chore: only build and deploy docs on the main jdx/hk repo

- pkl/builtins/stylelint.pkl
closes #121
Fixes mismatched internal stylelint `builtins/stylelint.pkl` export that doesn't match `Builtins.pkl` export name.
> fix: Mismatched stylelint pkl export #121

- mise.lock
- src/git.rs
- test/stash_prefers_unstaged_over_fixes.bats
• Prefer original unstaged stash contents only for conflicting hunks after fixers; preserve non-conflicting fixer edits.
• stash=git: apply stash; if conflicts, resolve markers by preferring the stash side per-file and stage; drop stash.
• stash=patch-file: apply patch with --3way; if conflict markers remain, resolve them by preferring patch (stash) hunks; keep other edits.
• Add Bats test validating both modes: test/stash_prefers_unstaged_over_fixes.bats.
• Implementation: textual conflict-marker resolver to prefer "theirs"/stash hunks without discarding unrelated changes.
• Include mise.lock.
> feat(stash): prefer unstaged contents on conflict; add tests

- pkl/builtins/mix_compile.pkl
- pkl/builtins/mix_test.pkl
Fix the elixir builtin names to not conflict.
The pkl builtin needs to be updated as well, via https://github.com/jdx/hk/pull/138
> fix: elixir steps named properly

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- json5 support for prettier builtin by [@tpansino](https://github.com/tpansino) in [#136](https://github.com/jdx/hk/pull/136)
- elixir steps named properly by [@paradox460](https://github.com/paradox460) in [#140](https://github.com/jdx/hk/pull/140)
- pkl builtin by [@tpansino](https://github.com/tpansino) in [#138](https://github.com/jdx/hk/pull/138)
- make glob, exclude, and stage relative to dir by [@jdx](https://github.com/jdx) in [#142](https://github.com/jdx/hk/pull/142)
- Prettier *.yml and *.md files by [@tpansino](https://github.com/tpansino) in [#141](https://github.com/jdx/hk/pull/141)
- @tpansino made their first contribution in [#141](https://github.com/jdx/hk/pull/141)
> chore: release v1.5.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- make stderr display in progress bars configurable by [@jdx](https://github.com/jdx) in [#155](https://github.com/jdx/hk/pull/155)
- properly display aborted steps when fail-fast triggers by [@jdx](https://github.com/jdx) in [#154](https://github.com/jdx/hk/pull/154)
> chore: release v1.7.0

- src/hook.rs
- src/step.rs
- test/profile_skip_summary.bats
- test/skip_output.bats
- test/skip_reason_precedence.bats
- test/skip_reasons_config.bats
This changes skip reason precedence so steps are skipped for more specific reasons before profile checks:
- NoFilesToProcess now takes precedence over ProfileNotEnabled.
- ConditionFalse now takes precedence over ProfileNotEnabled.
Tests:
- Added test/skip_reason_precedence.bats to cover both cases.
Implementation notes:
- Removed early profile skip in build_step_jobs; defer until after file filtering.
- In run(), evaluate condition first, then apply profile skip.
This maintains existing messaging controls via display_skip_reasons and keeps early exit behavior intact.
> fix: make NoFilesToProcess/ConditionFalse take precedence over ProfileNotEnabled

- docs/configuration.md
- docs/environment_variables.md
- hk.pkl
- pkl/Config.pkl
- pkl/builtins/cargo_check.pkl
- src/env.rs
- src/hook.rs
- src/step.rs
- test/output_summary.bats
Adds per-step output summaries with modes: stderr (default), stdout, combined (interleaved), and hide. Aggregates and prints once per step with headers. In text mode, summaries are disabled by default unless HK_SUMMARY_TEXT=1. Includes Pkl schema, docs, and Bats tests.
> feat(step): per-step output summaries (stderr|stdout|combined|hide)

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- **(test)** make sandbox opt-in via {{tmp}}; clean fixtures on success; fix builtins to use {{tmp}}; docs: update examples by [@jdx](https://github.com/jdx) in [#182](https://github.com/jdx/hk/pull/182)
- subtree-sync by [@jdx](https://github.com/jdx) in [#184](https://github.com/jdx/hk/pull/184)
> chore: release v1.9.1

- clx/src/progress.rs
- src/hook.rs
- Add progress_bar(flex=true) which auto-sizes to available width and wraps itself in flex tags\n- Update header template to use it; no need for `| flex` pipe\n- Add unit tests and ensure no overflow\n
> feat(progress): flex-width progress bar

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- **(clx)** avoid Unicode slicing panic in truncate_text and previews by using char-safe prefix by [@jdx](https://github.com/jdx) in [3369b59](https://github.com/jdx/hk/commit/3369b591910d2bbdc36f8055021f469c307563ca)
> chore: release v1.10.1

- mise-tasks/release-plz
Automate publishing of sub-crates (clx, ensembler, xx) when changed and push subtree commits during release. Adds subtree push before hk publish, detects local subtree deltas to bump sub-crate versions and changelogs, and includes sub-crate dirs in the release PR.
> chore: release-plz publish sub-crates and push subtrees

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- use correct expr environment with builtins by [@jdx](https://github.com/jdx) in [2284b33](https://github.com/jdx/hk/commit/2284b334200b5cb17dd06536b84755bf85778021)
- correct expr examples for git staged file syntax by [@jdx](https://github.com/jdx) in [f1fa1cf](https://github.com/jdx/hk/commit/f1fa1cfebec13cd03b1fb867777af477d433a3fe)
> chore: release v1.10.2

- docs/.vitepress/config.mts
Fixes VitePress rendering issue where inline code containing double curly braces was being interpreted as Vue template syntax instead of literal text.
Strings containing `{{}}` were not displayed correctly in https://hk.jdx.dev/configuration.html.
I solved it using the method introduced in https://github.com/vuejs/vitepress/discussions/3724.
> fix(docs): add v-pre directive to inline code for proper rendering

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- **(step)** include root variant for '**/' stage globs (stage maintainers.yml at repo root) by [@jdx](https://github.com/jdx) in [#198](https://github.com/jdx/hk/pull/198)
- fix msrv job by [@jdx](https://github.com/jdx) in [5590e22](https://github.com/jdx/hk/commit/5590e2293f84907a142bd34334dbd0164bb050b6)
> chore: release v1.10.3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- **(cache)** run init after loading cached config to apply warnings/settings\n\nFixes missing profile summary not showing on cached runs. Also ensures env/settings side-effects from config are applied consistently whether read fresh or from cache. by [@jdx](https://github.com/jdx) in [3b08788](https://github.com/jdx/hk/commit/3b08788956718d82e1f612e83cf36b6059e03365)
> chore: release v1.10.6

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- **(test)** support before/after commands in hk test by [@jdx](https://github.com/jdx) in [#214](https://github.com/jdx/hk/pull/214)
- support fail_fast in hk.pkl (env > config) by [@jdx](https://github.com/jdx) in [#212](https://github.com/jdx/hk/pull/212)
- remove period from missin-profile message by [@jdx](https://github.com/jdx) in [5f525a4](https://github.com/jdx/hk/commit/5f525a46e0815c0179f0a49d5bd25656a1e7f0f3)
- add pre-commit task to mise.toml generation by [@jdx](https://github.com/jdx) in [#217](https://github.com/jdx/hk/pull/217)
- Add missing code block end marker by [@karouf](https://github.com/karouf) in [#213](https://github.com/jdx/hk/pull/213)
- add pkl linter in Builtins by [@aheritier](https://github.com/aheritier) in [#210](https://github.com/jdx/hk/pull/210)
- set …
> chore: release v1.11.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- remove gh release create from release-plz by [@jdx](https://github.com/jdx) in [ae69d4a](https://github.com/jdx/hk/commit/ae69d4acc39f95752a32907c53e89476da5366bc)
> chore: release v1.11.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- include pkl packages in releases by [@jdx](https://github.com/jdx) in [#227](https://github.com/jdx/hk/pull/227)
- improve stashing error handling and robustness by [@jdx](https://github.com/jdx) in [#229](https://github.com/jdx/hk/pull/229)
> chore: release v1.12.1

- docs/configuration.md
- mise.lock
- src/git.rs
- src/hook.rs
- test/pre_commit_partial_staged.bats
Summary
- Fix incorrect handling of partially staged files during pre-commit so unstaged hunks remain in the worktree and only staged hunks are committed.
- Treat stash = true as a boolean alias for "git"; keep "patch-file" as an alias of "git" for now.
- Honor the provided environment stash method in resolve_stash_method.
Changes
- hk/src/git.rs: Pass file subset to stashing; force shell Git for partial stash; safely handle non‑UTF‑8 pathspecs; preserve/restore index correctly.
- hk/src/hook.rs: Fix resolve_stash_method to use the passed env value and remove unreachable code.
- hk/docs/configuration.md: Document boolean stash, note patch-file alias.
- hk/test/pre_commit_partial_staged.bats: Tests for both git and patch-file modes.
Testing
- Built and ran Bats tests with and without …
> fix: pre-commit partial staging: honor env stash, alias patch-file, robust partial stash

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- add tracing and performance diagnostics support by [@jdx](https://github.com/jdx) in [3045a38](https://github.com/jdx/hk/commit/3045a3826e4b1c4213dbccadb7dc1ce442a814fa)
- add tracing and performance diagnostics support by [@jdx](https://github.com/jdx) in [#259](https://github.com/jdx/hk/pull/259)
- comprehensive configuration unification with proper precedence and union semantics by [@jdx](https://github.com/jdx) in [#266](https://github.com/jdx/hk/pull/266)
- centralized skip configuration for steps and hooks by [@jdx](https://github.com/jdx) in [#268](https://github.com/jdx/hk/pull/268)
- add comprehensive schema reference and built-in linters documentation by [@jdx](https://github.com/jdx) in [#261](https://github.com/jdx/hk/pull/261)
- add comprehensive logging and debugging guide …
> chore: release v1.13.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- correct pkl package artifact path in release workflow by [@jdx](https://github.com/jdx) in [#271](https://github.com/jdx/hk/pull/271)
> chore: release v1.13.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- use simple directory path for pkl artifact upload by [@jdx](https://github.com/jdx) in [#272](https://github.com/jdx/hk/pull/272)
> chore: release v1.13.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- diagnose pkl package failure in release workflow by [@jdx](https://github.com/jdx) in [#274](https://github.com/jdx/hk/pull/274)
> chore: release v1.13.3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- explicitly install pkl and run package command directly by [@jdx](https://github.com/jdx) in [#276](https://github.com/jdx/hk/pull/276)
> chore: release v1.13.4

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- fix build-pkl upload path to use mise dist (docs/public/pkl) by [@jdx](https://github.com/jdx) in [6745830](https://github.com/jdx/hk/commit/6745830a9f5f4bb949216b682ba501119aa4262f)
> chore: release v1.13.6

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/config.md
- docs/cli/config/explain.md
- docs/cli/config/show.md
- docs/cli/index.md
- hk.usage.kdl
- centralized settings registry with codegen by [@jdx](https://github.com/jdx) in [#284](https://github.com/jdx/hk/pull/284)
- removed snapshot file by [@bhanuprasad14](https://github.com/bhanuprasad14) in [0952af5](https://github.com/jdx/hk/commit/0952af5dc4516a309d93da74155935c48eed81d1)
- Extract Pkl error handling into separate method by [@jdx](https://github.com/jdx) in [e62cb24](https://github.com/jdx/hk/commit/e62cb2490c6917fe70836b543e532348cd3722f4)
> chore: release v1.14.0

- src/git.rs
- src/merge.rs
- test/pre_commit_does_not_stash_staged_only_files.bats
- test/pre_commit_preserves_eof_newline.bats
- test/pre_commit_prettier_commits_fixer_changes.bats
Summary
- Preserve exact EOF newline during manual-unstash (newline-only detection)
- Snapshot pre-stash worktree; re-stage from current index post-fixers
- Skip stashing when subset has no unstaged hunks (scoped diff/status/ls-files)
- Trace diagnostics for base/index/worktree/fixer and merged summaries
- Merge: prefer fixer when worktree == base on region
- Prettier builtin reverted to defaults; tests accept single/double quotes
- Bats env fix (HK_SUMMARY_TEXT) and status expectation tweak
- Rustfmt; full CI green
Commits
- git: preserve EOF newline state during manual unstash; snapshot worktree pre-stash; re-stage from saved index (2893744)
- tests: export HK_SUMMARY_TEXT in setup; remove ineffective per-run check (e31f409)
- git: skip stash when subset has no unstaged hunks; tests: …
> fix: prettier bugs; stash/unstash robustness; preserve EOF newline

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/check.md
- docs/cli/commands.json
- docs/cli/fix.md
- docs/cli/index.md
- docs/cli/run.md
- docs/cli/run/commit-msg.md
- docs/cli/run/pre-commit.md
- docs/cli/run/pre-push.md
- docs/cli/run/prepare-commit-msg.md
- hk.usage.kdl
- prevent duplicate _type fields in JSON cache for groups by [@jdx](https://github.com/jdx) in [#297](https://github.com/jdx/hk/pull/297)
- add top-level exclude property to hk.pkl by [@jdx](https://github.com/jdx) in [#299](https://github.com/jdx/hk/pull/299)
> chore: release v1.15.3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/cli/commands.json
- docs/cli/index.md
- hk.usage.kdl
- ensure stash cleanup by [@jdx](https://github.com/jdx) in [#302](https://github.com/jdx/hk/pull/302)
> chore: release v1.15.5
